minify: true

scheme: Mist

favicon:
  small: /images/favicon-16x16-scallop.png
  medium: /images/favicon-32x32-scallop.png
  apple_touch_icon: /images/apple-touch-icon-scallop.png
  safari_pinned_tab: /images/scallop.svg
  #android_manifest: /manifest.json

sidebar:
  display: always

avatar:
  url: https://avatars.githubusercontent.com/zhengqingquan

social:
  GitHub: https://github.com/zhengqingquan || fab fa-github

menu:
  home: / || fa fa-home
  categories: /categories/ || fa fa-th
  tags: /tags/ || fa fa-tags
  archives: /archives/ || fa fa-archive
  projects: /projects/ || fa fa-code

footer:
  since: 2024
  powered: false

# Automatically insert whitespace between CJK and half-width characters.
# For more information: https://github.com/vinta/pangu.js
# Server-side plugin: https://github.com/next-theme/hexo-pangu
pangu: true

local_search:
  enable: true

# Font See: https://fonts.google.com/
font:
  enable: true
  global:
    # See:
    # Josefin Sans: https://github.com/googlefonts/josefinsans
    # Noto Serif SC: https://github.com/notofonts/noto-cjk
    family: Josefin Sans, Noto Serif SC

motion:
  enable: false

read_more_btn: false

# Codeblock: one-click copy (hover to show)
# style: default | flat | mac
codeblock:
  copy_button:
    enable: true
    style: default

back2top:
  enable: false

# Table of Contents in the Sidebar
# Front-matter variable (nonsupport wrap expand_all).
toc:
  # Automatically add list number to toc.
  number: false
  # If true, all level of TOC in a post will be displayed, rather than the activated part of it.
  expand_all: true

# # Show Views / Visitors of the website / page with busuanzi.
# # For more information: http://ibruce.info/2015/04/04/busuanzi/
busuanzi_count:
  enable: true

custom_file_path:
  head: source/_data/head.njk
  style: source/_data/styles.styl
  bodyEnd: source/_data/body-end.njk

