scheme: Mist

sidebar:
  display: always

avatar:
  url: https://avatars.githubusercontent.com/zhengqingquan

menu:
  home: / || fa fa-home
  archives: /archives/ || fa fa-archive

footer:
  powered: false

local_search:
  enable: true
