minify: true

scheme: Mist

sidebar:
  display: always

avatar:
  url: https://avatars.githubusercontent.com/zhengqingquan

menu:
  home: / || fa fa-home
  categories: /categories/ || fa fa-th
  tags: /tags/ || fa fa-tags
  archives: /archives/ || fa fa-archive

footer:
  powered: false

# Automatically insert whitespace between CJK and half-width characters.
# For more information: https://github.com/vinta/pangu.js
# Server-side plugin: https://github.com/next-theme/hexo-pangu
pangu: true

local_search:
  enable: true

# Font See: https://fonts.google.com/
font:
  enable: true
  global:
    # See:
    # Josefin Sans: https://github.com/googlefonts/josefinsans
    # Noto Serif SC: https://github.com/notofonts/noto-cjk
    family: Josefin Sans, Noto Serif SC

motion:
  enable: false
